backend = "glx";

vsync = true;
corner-radius = 12;

active-opacity = 0.9;
inactive-opacity = 0.75;

blur-method = "none";


opacity-rule = [
    "100:class_g = 'zen-beta'",
    "100:class_g = 'discord'"
];

rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
];
